### ISSUE TITLE
Python error when adding the node

### ISSUE THREAD

**Issue by AlexFundorin** [jlampel/voronoi_scatter#1]
Blender 3.0.0
I'm simply trying to add scatter to the default cube, using random texture - https://i.imgur.com/62l1BNj.png
And this is the node I'm seeing - https://i.imgur.com/x6jm9d3.png

**Comment by jlampel** [comment]
Hey Alex, thank you for letting me know! Is this from GitHub, from CG Cookie, or from the Blender Market? The GitHub repository has all the code for the addon but doesn't have the .blend files that go with it. Apologies for any confusion - I should have written up a readme for this.

**Comment by AlexFundorin** [comment]
I see. This is a GH version. Everything's fine, then.
